[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc-version = "0.8.19"

[fuzz]
runs=1000
depth=1000

[invariant]
runs=1000
depth=1000
fail_on_revert=true

[rpc_endpoints]
fork = "http://127.0.0.1:8545"
frame = "http://127.0.0.1:1248"